# Generated by Django 4.2.7 on 2024-02-08 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_text_news_body_remove_news_publish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 10, 37, 40, 516725, tzinfo=datetime.timezone.utc)),
        ),
    ]
