# Generated by Django 4.2.7 on 2024-02-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
    ]
